export const data = [
    {
        id: 1,
        image: '/images/linen.jpg',
        name: 'Nike Air Force 1 Low Linen Kith Exclusive',
        category: 'Nike',
        price: '7,495.00',
        history: 'One of the most prolific collaborators in the fashion world, Kith, has recently been seen working with BMW on an ultra-limited edition version of the BMW i4, though the NYC-based retailer and label is still dabbling in the fashion world. Often taking to Instagram to share upcoming releases, Kiths founder, Ronnie Fieg, has just teased two colorways of an upcoming Kith x Asics collaboration that features two colorways on the EX-89.',
    },
    {
        id: 2,
        image: '/images/spzl.jpg',
        name: 'Adidas LG Spzl x Liam Gallagher',
        category: 'Adidas',
        price: '8,000.00',
        history: 'One of the most prolific collaborators in the fashion world, Kith, has recently been seen working with BMW on an ultra-limited edition version of the BMW i4, though the NYC-based retailer and label is still dabbling in the fashion world. Often taking to Instagram to share upcoming releases, Kiths founder, Ronnie Fieg, has just teased two colorways of an upcoming Kith x Asics collaboration that features two colorways on the EX-89.',
    },
    {
        id: 3,
        image: '/images/sb1.jpg',
        name: 'Nike SB Dunk Low "London"',
        category: 'Nike',
        price: '8,550.00',
        history: 'One of the most prolific collaborators in the fashion world, Kith, has recently been seen working with BMW on an ultra-limited edition version of the BMW i4, though the NYC-based retailer and label is still dabbling in the fashion world. Often taking to Instagram to share upcoming releases, Kiths founder, Ronnie Fieg, has just teased two colorways of an upcoming Kith x Asics collaboration that features two colorways on the EX-89.',
    },
    {
        id: 4,
        image: '/images/tom.jpg',
        name: 'NikeCraft General Purpose Shoe x Tom Sachs',
        category: 'Nike',
        price: '9,850.00',
        history: 'One of the most prolific collaborators in the fashion world, Kith, has recently been seen working with BMW on an ultra-limited edition version of the BMW i4, though the NYC-based retailer and label is still dabbling in the fashion world. Often taking to Instagram to share upcoming releases, Kiths founder, Ronnie Fieg, has just teased two colorways of an upcoming Kith x Asics collaboration that features two colorways on the EX-89.',
    },
    {
        id: 5,
        image: '/images/unc.jpg',
        name: 'Air Jordan 1 High UNC',
        category: 'Jordan',
        price: '10,045.00',
        history: 'One of the most prolific collaborators in the fashion world, Kith, has recently been seen working with BMW on an ultra-limited edition version of the BMW i4, though the NYC-based retailer and label is still dabbling in the fashion world. Often taking to Instagram to share upcoming releases, Kiths founder, Ronnie Fieg, has just teased two colorways of an upcoming Kith x Asics collaboration that features two colorways on the EX-89.',
    },
    {
        id: 6,
        image: '/images/fleur.jpg',
        name: 'Converse Chuck Chenille',
        category: 'Converse',
        price: '8,095.00',
        history: 'One of the most prolific collaborators in the fashion world, Kith, has recently been seen working with BMW on an ultra-limited edition version of the BMW i4, though the NYC-based retailer and label is still dabbling in the fashion world. Often taking to Instagram to share upcoming releases, Kiths founder, Ronnie Fieg, has just teased two colorways of an upcoming Kith x Asics collaboration that features two colorways on the EX-89.',
    },
    {
        id: 7,
        image: '/images/unc1.jpg',
        name: 'Jordan 1 Low SB UNC',
        category: 'Jordan',
        price: '6,495.00',
        history: 'One of the most prolific collaborators in the fashion world, Kith, has recently been seen working with BMW on an ultra-limited edition version of the BMW i4, though the NYC-based retailer and label is still dabbling in the fashion world. Often taking to Instagram to share upcoming releases, Kiths founder, Ronnie Fieg, has just teased two colorways of an upcoming Kith x Asics collaboration that features two colorways on the EX-89.',
    },
    {
        id: 8,
        image: '/images/tokyo.jpg',
        name: 'Nike SB Dunk Low “Tokyo”',
        category: 'Nike',
        price: '7,895.00',
        history: 'One of the most prolific collaborators in the fashion world, Kith, has recently been seen working with BMW on an ultra-limited edition version of the BMW i4, though the NYC-based retailer and label is still dabbling in the fashion world. Often taking to Instagram to share upcoming releases, Kiths founder, Ronnie Fieg, has just teased two colorways of an upcoming Kith x Asics collaboration that features two colorways on the EX-89.',
    },
    {
        id: 9,
        image: '/images/89.jpg',
        name: 'Kith x Asics - E89',
        category: 'Asics',
        price: '10,400.00',
        history: 'One of the most prolific collaborators in the fashion world, Kith, has recently been seen working with BMW on an ultra-limited edition version of the BMW i4, though the NYC-based retailer and label is still dabbling in the fashion world. Often taking to Instagram to share upcoming releases, Kiths founder, Ronnie Fieg, has just teased two colorways of an upcoming Kith x Asics collaboration that features two colorways on the EX-89.',
    },
    {
        id: 10,
        image: '/images/dunk.jpg',
        name: 'Nike SB Dunk x Concepts',
        category: 'Nike',
        price: '6,495.00',
        history: 'One of the most prolific collaborators in the fashion world, Kith, has recently been seen working with BMW on an ultra-limited edition version of the BMW i4, though the NYC-based retailer and label is still dabbling in the fashion world. Often taking to Instagram to share upcoming releases, Kiths founder, Ronnie Fieg, has just teased two colorways of an upcoming Kith x Asics collaboration that features two colorways on the EX-89.',
    },
    {
        id: 11,
        image: '/images/cdg.jpg',
        name: 'CdG PLAY x Converse Chuck Taylor',
        category: 'Converse',
        price: '7.495.00',
        history: 'One of the most prolific collaborators in the fashion world, Kith, has recently been seen working with BMW on an ultra-limited edition version of the BMW i4, though the NYC-based retailer and label is still dabbling in the fashion world. Often taking to Instagram to share upcoming releases, Kiths founder, Ronnie Fieg, has just teased two colorways of an upcoming Kith x Asics collaboration that features two colorways on the EX-89.',
    },
    {
        id: 12,
        image: '/images/sns.jpg',
        name: 'Vans Vault OG Authentic LX x SNS',
        category: 'Vans',
        price: '8,250.00',
        history: 'One of the most prolific collaborators in the fashion world, Kith, has recently been seen working with BMW on an ultra-limited edition version of the BMW i4, though the NYC-based retailer and label is still dabbling in the fashion world. Often taking to Instagram to share upcoming releases, Kiths founder, Ronnie Fieg, has just teased two colorways of an upcoming Kith x Asics collaboration that features two colorways on the EX-89.',
    },
    {
        id: 13,
        image: '/images/am1.jpg',
        name: 'Nike Air Max 1/97 x Sean Wotherspoon',
        category: 'Nike',
        price: '10,400.00',
        history: 'One of the most prolific collaborators in the fashion world, Kith, has recently been seen working with BMW on an ultra-limited edition version of the BMW i4, though the NYC-based retailer and label is still dabbling in the fashion world. Often taking to Instagram to share upcoming releases, Kiths founder, Ronnie Fieg, has just teased two colorways of an upcoming Kith x Asics collaboration that features two colorways on the EX-89.',
    },
    {
        id: 14,
        image: '/images/samba.jpg',
        name: 'Adidas Samba - OG',
        category: 'Adidas',
        price: '5,995.00',
        history: 'One of the most prolific collaborators in the fashion world, Kith, has recently been seen working with BMW on an ultra-limited edition version of the BMW i4, though the NYC-based retailer and label is still dabbling in the fashion world. Often taking to Instagram to share upcoming releases, Kiths founder, Ronnie Fieg, has just teased two colorways of an upcoming Kith x Asics collaboration that features two colorways on the EX-89.',
    },
    {
        id: 15,
        image: '/images/nb.jpg',
        name: 'New Balance 993 MiUSA Kith Pistachio',
        category: 'New Balance',
        price: '11,285.00',
        history: 'One of the most prolific collaborators in the fashion world, Kith, has recently been seen working with BMW on an ultra-limited edition version of the BMW i4, though the NYC-based retailer and label is still dabbling in the fashion world. Often taking to Instagram to share upcoming releases, Kiths founder, Ronnie Fieg, has just teased two colorways of an upcoming Kith x Asics collaboration that features two colorways on the EX-89.',
    },
    {
        id: 16,
        image: '/images/adi.jpg',
        name: 'Adidas Adizero Prime X',
        category: 'Adidas',
        price: '11,245.00',
        history: 'One of the most prolific collaborators in the fashion world, Kith, has recently been seen working with BMW on an ultra-limited edition version of the BMW i4, though the NYC-based retailer and label is still dabbling in the fashion world. Often taking to Instagram to share upcoming releases, Kiths founder, Ronnie Fieg, has just teased two colorways of an upcoming Kith x Asics collaboration that features two colorways on the EX-89.',
    },
]